/**
 * Rooms content collection — the two Kaivalyam accommodation entries.
 * --------------------------------------------------------------------
 * Feature: kaivalyam-homestay-website (task 4.2)
 *
 * Authors the typed {@link Room} data consumed by the Rooms page (task 11.3)
 * and the Home room-type summary (task 11.1):
 *   • `luxury-cottage` — the duplex luxury cottage (Req 4.2)
 *   • `classic-room`   — the affordable, cozy room (Req 4.3)
 *
 * Strongly typed against `content/types.ts`; no React, no side effects.
 *
 * Photos: intentionally left as EMPTY arrays. The real, optimized photo catalog
 * (with intrinsic width/height + AVIF/WebP variants) is OWNED and generated by
 * the build-time asset pipeline (task 5.1) — authoring asset paths here by hand
 * would fabricate files the pipeline controls. The Rooms page wires the
 * generated `night_ambiance`/`interiors`/`exteriors` photos in once 5.1 lands.
 *
 * bookingHref: resolves via `buildBookingUrl` per the {@link Room} contract
 * (Req 4.6) — every room booking action lands on the configured eeabsolute
 * Booking_Engine. We reuse the single canonical destination
 * {@link kaivalyamBookingUrl} so every "Book Now" / room booking action across
 * the site resolves to one place (design Property 1).
 *
 * _Requirements: 4.1, 4.2, 4.3, 4.4_
 */

import { kaivalyamBookingUrl } from '@/domain/integration-urls/booking-url';
import type { ImageAsset, Room } from './types';

/**
 * The canonical "Book Now" destination for both rooms. Derived from
 * `buildBookingUrl(kaivalyamBookingConfig)` (India / Kerala / Wayanad on
 * eeabsolute.com), so it satisfies Req 4.6 and design Property 1.
 */
const ROOM_BOOKING_HREF = kaivalyamBookingUrl();

/**
 * Photos are authored by the asset pipeline (task 5.1), not here. Empty until
 * then — see file header. Typed explicitly so the empty literal is a valid
 * `ImageAsset[]` under the discriminated-union model.
 */
const NO_PHOTOS_YET: ImageAsset[] = [];

/**
 * The duplex Luxury Cottage (Req 4.1, 4.2).
 *
 * Built for families and long-staying guests who want space and privacy: two
 * levels, an attached bathroom, a roof balcony and sit-out for the Wayanad
 * dusk, an indoor play area for children, private laundry, and a garden gazebo.
 */
export const luxuryCottage: Room = {
  id: 'luxury-cottage',
  name: 'Luxury Cottage',
  summary:
    'A private duplex cottage built for families — two levels, a roof balcony and sit-out, an indoor play area, and a garden gazebo, wrapped in hill-village quiet.',
  description:
    'The Luxury Cottage is a spacious duplex laid out for togetherness and privacy in equal measure. Downstairs opens onto the garden and a shaded gazebo; upstairs a roof balcony and sit-out catch the cool Wayanad evenings and the sound of the plantations settling for the night. An attached bathroom with hot water, a dedicated indoor play area for little ones, and private laundry mean a family can settle in comfortably for a long, unhurried stay. It is the most secluded corner of Kaivalyam — your own quiet world, a few steps from everything the homestay offers.',
  amenities: [
    'Duplex layout across two levels',
    'Attached bathroom with hot water',
    'Roof balcony and private sit-out',
    'Indoor play area for children',
    'Private laundry',
    'Garden gazebo',
    'Free high-speed Wi-Fi',
    'Free on-site parking',
    'Pet-friendly stay',
    'Daily housekeeping',
    'Home-cooked Malayali meals on request',
  ],
  // Authored by the asset pipeline (task 5.1) — see file header.
  photos: NO_PHOTOS_YET,
  bookingHref: ROOM_BOOKING_HREF,
};

/**
 * The Classic Room (Req 4.1, 4.3).
 *
 * An affordable, cozy room with the essentials done well and the same warm
 * hospitality — an easy, restful base for guests who want simplicity and calm.
 */
export const classicRoom: Room = {
  id: 'classic-room',
  name: 'Classic Room',
  summary:
    'An affordable, cozy room with the essentials done well — comfortable, calm, and warmly looked after, an easy base for your Wayanad days.',
  description:
    'The Classic Room keeps things simple and restful: comfortable bedding, a clean attached bathroom with hot water, and the quiet that Kaivalyam is named for. It is the affordable way to wake to birdsong and plantation air without giving up comfort or the homestay\u2019s warm, attentive hospitality. Step out to the garden, the library, or a home-cooked meal — everything that makes a stay here feel like time genuinely your own.',
  amenities: [
    'Comfortable double bedding',
    'Clean attached bathroom with hot water',
    'Free high-speed Wi-Fi',
    'Free on-site parking',
    'Pet-friendly stay',
    'Daily housekeeping',
    'Home-cooked Malayali meals on request',
    'Garden and library access',
  ],
  // Authored by the asset pipeline (task 5.1) — see file header.
  photos: NO_PHOTOS_YET,
  bookingHref: ROOM_BOOKING_HREF,
};

/**
 * Both rooms in display order (Luxury Cottage first), for the Rooms page and
 * the Home room-type summary. Typed `readonly Room[]` so the canonical
 * collection cannot be mutated by consumers.
 */
export const rooms: readonly Room[] = [luxuryCottage, classicRoom] as const;
